# Generated by Django 4.1.dev20211124163835 on 2021-11-25 17:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(default='Employee', max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=60, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('contact_info', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=50)),
                ('first_doze', models.BooleanField()),
                ('first_doze_date', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('second_doze', models.BooleanField()),
                ('second_doze_date', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vaccination_drive.userdetails')),
            ],
        ),
    ]
