# Generated by Django 4.1.dev20211124163835 on 2021-11-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_drive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='vaccinationdetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaccination_drive.userdetails'),
        ),
    ]
