# Generated by Django 4.1.dev20211124163835 on 2021-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_drive', '0005_alter_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
