# Generated by Django 4.1.dev20211124163835 on 2021-11-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_drive', '0007_remove_userdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
